services:
  - type: web
    name: calendar-event
    env: node
    buildCommand: 'npm install express googleapis body-parser express-session'
    startCommand: 'node index.js'
    envVars:
      - key: CLIENT_ID
        fromDatabase:
          name: CLIENT_ID
          defaultValue: "your-default-client-id" # Optional, you can leave this empty
      - key: CLIENT_SECRET
        fromDatabase:
          name: CLIENT_SECRET
          defaultValue: "your-default-client-secret" # Optional, you can leave this empty
      - key: REDIRECT_URI
        fromDatabase:
          name: REDIRECT_URI
          defaultValue: "your-default-redirect-uri" # Optional, you can leave this empty
